import Constants from 'expo-constants'

//Type for response

export type ClimbAnalysisResponse = {
  task_id: string
}

//Use expo constant to get IP to send req to DEV ONLY

const host = Constants.expoConfig?.hostUri?.split(':')[0] ?? 'localhost'
export const API_URL = `http://${host}:8000`

//idempotencyKey is generated by the caller (once per submission attempt), not
//defaulted here if the mutation ever gets retries enabled, retries
//reuse the same key instead of each attempt making a new one.

//No photo here - detection already happened via /detect (see api/detectHolds.tsx)
//before the user ever started tapping, so submission only needs to reference
//that detection_id plus which of its detections the user selected.

export type ClimbAnalysisVariables = {
  detectionId: string
  idempotencyKey: string
  selectedHoldIds: number[]
}

export async function climbAnalysis({
  detectionId,
  idempotencyKey,
  selectedHoldIds,
}: ClimbAnalysisVariables): Promise<ClimbAnalysisResponse> {
  const formData = new FormData()
  formData.append('detection_id', detectionId)
  formData.append('selected_hold_ids', JSON.stringify(selectedHoldIds))

  const res = await fetch(`${API_URL}/analysis`, {
    method: 'POST',
    headers: { 'Idempotency-Key': idempotencyKey },
    body: formData,
  })

  if (!res.ok) throw new Error(`Analysis failed: ${res.status}`)
  return (await res.json()) as ClimbAnalysisResponse
}
